export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST' // 获取文章数据列表
export const SET_EDITOR_ARTICLE = 'SET_EDITOR_ARTICLE' // 设置正在编辑的文章
export const ADD_ARTICLE = 'ADD_ARTICLE'  // 添加文章
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS' // 获取文章成功
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE' // 获取文章失败
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS' // 更新文章成功
export const UPDATE_ARTICLE_FAILURE = 'UPDATE_ARTICLE_FAILURE' // 更新文章失败
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS' // 添加文章成功
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE' // 添加文章失败

